default:
  server:
    port: 4845
    buildInfo:
      productName: "DummySkillServer - Add"
      buildNumber: "v0001"
    ip: "0.0.0.0"
    endpointName: 'OPCUA@Siemens'
    username: 'root'
    password: 'root'
    allowAnonymous: true,
    discoverySerer: null #'opc.tcp://Laplace.faps.uni-erlangen.de:48400'
    serverInfo:
      applicationUri: "http://siemens.com/SkillOPCUA/AddV1"
      productUri: "siemens.com/SP347_Example"
      applicationName: "SP347SkillEngineering@Siemens" 
    serverNodeSet: ["Add_V1.xml"]